#pragma once
#include <string>
using namespace std;

#define NO_ERROR_CODE 0
// communicate error
#define ERROR_CODE_SOCKET_OTHER_ERROR -1000
#define ERROR_CODE_WSASTART_FAIL -1001  // not used
#define ERROR_CODE_CREATE_SOCKET_FAIL -1002
#define ERROR_CODE_BIND_PORT_FAIL -1003
#define ERROR_CODE_SOCKET_READ_FAIL -1004
#define ERROR_CODE_SOCKET_TIMEOUT -1005
#define ERROR_CODE_RECVFROM_FAIL -1006
#define ERROR_CODE_SENDTO_FAIL -1007
#define ERROR_CODE_LOST_HEARTBEAT -1008
#define ERROR_CODE_LOST_ROBOTSTATE -1009
#define ERROR_CODE_GET_DH_FAILED -1010
#define ERROR_CODE_RELEASE_BRAKE_FAILED -1011  // not used
#define ERROR_CODE_HOLD_BRAKE_FAILED -1012     // not used
// robot error
#define ERROR_CODE_JOINT_REGIST_ERROR -2001  // brake to remove error
#define ERROR_CODE_COMMUNICATE_ERROR -2101
#define ERROR_CODE_CALLING_CONFLICT_ERROR -2201
#define ERROR_CODE_COLLISION_ERROR -2202
#define ERROR_CODE_NOT_FOLLOW_POSITION_CMD -2203
#define ERROR_CODE_NOT_FOLLOW_TCP_CMD -2204
#define ERROR_CODE_NOT_ALL_AT_OP_STATE -2205  // brake to remove error
#define ERROR_CODE_OUT_RANGE_FEEDBACK -2206
#define ERROR_CODE_EMERGENCY_STOP -2207
#define ERROR_CODE_NO_INIT_PARAMETER -2208
#define ECODE_NOT_MATCH_LOAD -2209
#define ERROR_CODE_PLAN_ERROR -2301
#define ERROR_CODE_INTERPOLATE_POSITION_ERROR -2302
#define ERROR_CODE_INTERPOLATE_TORQUE_ERROR -2303
#define ERROR_CODE_SINGULAR_VALUE_ERROR -2304
// other error
#define ERROR_CODE_RESOURCE_UNAVAILABLE -3001
#define ERROR_CODE_DUMP_LOG_TIMEOUT -3002
#define ERROR_CODE_DUMP_LOG_FAILED -3003  // cant find source log files
#define RESET_DH_FAILED -3004             // cant find source log files

//#define TEACH_PENDANT_SERVER_IP      "192.168.3.87"//"127.0.0.1"//
#define TEACH_PENDANT_SERVER_IP "192.168.10.75"  //"127.0.0.1"//
#define LOCAL_IP "127.0.0.1"                     //"192.168.3.87"//

#define TEACH_PENDANT_SERVER_PORT 8888
#define TEACH_PENDANT_SERVER_TIMEOUT 1000  // 1s
#define LOCAL_PORT 0                       // 9999

#define HEARTBEAT_SERVER_PORT 4444
#define HEARTBEAT_SLEEP_TIME 100  // 100ms
#define HEARTBEAT_TIMEOUT 1000    // 1s
#define LOCAL_HEARTBEAT_PORT 0    // 5555

#define ROBOT_STATE_SERVER_PORT 6666
#define ROBOT_STATE_SLEEP_TIME 10  // 10ms
#define ROBOT_STATE_TIMEOUT 1000   // 1s
#define LOCAL_ROBOT_STATE_PORT 0   // 7777

#define REALTIME_CONTROL_PORT 3333
#define LOCAL_REALTIME_PORT 0

#define CONST_JOINT_COUNT 7
#define CONST_POSE_SIZE 6
#define ERROR_MESSAGE_LEN 64
#define CONST_JACOBI_MATRIX_SIZE 42
