controller_list:
  - name: fake_medical_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses.
  - group: medical
    pose: home